//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.02 at 10:08:05 AM CET 
//


package com.sedaq.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PersonById" type="{http://sedaq.com/ws}PersonById"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personById"
})
@XmlRootElement(name = "GetPersonByIdResponse")
public class GetPersonByIdResponse {

    @XmlElement(name = "PersonById", required = true)
    protected PersonById personById;

    /**
     * Gets the value of the personById property.
     * 
     * @return
     *     possible object is
     *     {@link PersonById }
     *     
     */
    public PersonById getPersonById() {
        return personById;
    }

    /**
     * Sets the value of the personById property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonById }
     *     
     */
    public void setPersonById(PersonById value) {
        this.personById = value;
    }

}
